### ISSUE TITLE
Is there a way to have label and value on separate lines?

### ISSUE THREAD

**Issue by scott-laursen** [Dean177/react-native-json-tree#128]
Great tool - thank you!

As the title says I would like to hear if there is a way to have the label and content on separate lines. The problem happens when the value is very long and I try to show it on a phone in portrait.

**Comment by Dean177** [comment]
Take a look at the https://github.com/Dean177/react-native-json-tree#customize-rendering section. If it doesn't help / work, let me know and I will take a closer look.

**Comment by Dean177** [comment]
@scott-laursen did you manage to get the layout you were going for?
