### ISSUE TITLE
`react-base16-styling` package is specified as a git dependency in `yarn.lock`

### ISSUE THREAD

**Issue by gisenberg** [Dean177/react-native-json-tree#137]
`react-base16-styling` should be a package dependency rather than a git dependency.

**Comment by Dean177** [comment]
base16 is currently including a .babelrc in its npm package. This is a problem when used with react native as it is using some deprecated options.

**Comment by Dean177** [comment]
See this issue on [base16-js](https://github.com/base16-js/issues/3). 
I intend to create a PR to add an .npmingore file which excludes the .babelrc but its not a priority for me, but that library hasn't been updated in a fair while so it may be some time before this issue is resolved.
