### ISSUE TITLE
Peer dependency warning on react-native 48

### ISSUE THREAD

**Issue by TheaLanherne** [Dean177/react-native-json-tree#138]
After upgrading our project to the latest version of react-native (0.48.4), we see the following warning when running yarn install:

> warning "react-native-json-tree@1.0.0" has incorrect peer dependency "react-native@^0.43.2".

However I think that it would probably be safe for you to just update your peer dependency, because react-native-json-tree seems to work fine when we run the app.

**Comment by Dean177** [comment]
Fixed in v1.1.0
