### ISSUE TITLE
expected a functiom

### ISSUE THREAD

**Issue by zisheng-ai** [Dean177/react-native-json-tree#146]
如果开启 `inlineRequires` 就会出现这个问题

![image](https://user-images.githubusercontent.com/13204332/59778617-6d484980-92e9-11e9-89ee-ae8985dc9166.png)

**Comment by zisheng-ai** [comment]
https://github.com/Dean177/base16-js/blob/master/lib/bright.js

**Comment by Dean177** [comment]
Can you paste the full error you are getting?
Perhaps you can provide an example?

**Comment by zisheng-ai** [comment]
- react-native-json-tree/src/index.js 68:57
- https://github.com/Dean177/base16-js/blob/master/lib/bright.js

**Comment by zisheng-ai** [comment]
just set inlineRequires to true, you can see it

**Comment by zisheng-ai** [comment]
maybe 

![image](https://user-images.githubusercontent.com/13204332/59779362-ae8d2900-92ea-11e9-9b80-c1d300f98d50.png)

**Comment by Oliverxyj123** [comment]
请问怎么解决呢？

**Comment by Dean177** [comment]
Ah, I closed the wrong one. #151 is a duplicate of this issue
