### ISSUE TITLE
Expected a function

### ISSUE THREAD

**Issue by Oliverxyj123** [Dean177/react-native-json-tree#151]
![image](https://user-images.githubusercontent.com/15978950/83950935-d9a4bb80-a860-11ea-812c-64bfce45ef3b.png)
When I debug this code, something is wrong here
![image](https://user-images.githubusercontent.com/15978950/83950966-0eb10e00-a861-11ea-9fa8-800ef95b6212.png)
How can I do that?

**Comment by Oliverxyj123** [comment]
![image](https://user-images.githubusercontent.com/15978950/83950979-28525580-a861-11ea-9b7f-5f33a57d07ec.png)

**Comment by hemantgogia09** [comment]
I am facing same problem were you able to solve it @Oliverxyj123 ?

**Comment by Grewer** [comment]
This bug originates from the `react-base16-styling` library
This code:
```
var _lodash3 = require('lodash.flow')
var _lodash4 = _interopRequireDefault(_lodash3)
var rgb = require('color-space/rgb')


var invertColor = (0, _lodash4.default)(_parse2.default, rgb.yuv, function(_ref) {
  var _ref2 = _slicedToArray(_ref, 3), y = _ref2[0], u = _ref2[1], v = _ref2[2]
  return [flip(y), u, v]
}, yuv.rgb, _rgb2hex2.default)
```
`lodash.flow`, which accepts multiple function

rgb:
```
'use strict'

module.exports = {
	name: 'rgb',
	min: [0,0,0],
	max: [255,255,255],
	channel: ['red', 'green', 'blue'],
	alias: ['RGB']
};
```
yuv.rgb:
```
var rgb = require('./rgb');

var yuv = module.exports = {
	name: 'yuv',
	min: [0,-0.5,-0.5],
	max: [1, 0.5, 0.5],
	channel: ['Y','U','V'],
	alias: ['YUV', 'EBU'],

};

yuv.rgb = function(yuv) {
	var y = yuv[0],
		u = yuv[1],
		v = yuv[2],
		r, g, b;

	r = (y * 1) + (u *  0) + (v * 1.13983);
	g = (y * 1) + (u * -0.39465) + (v * -0.58060);
	b = (y * 1) + (u * 2.02311) + (v * 0);

	r = Math.min(Math.max(0, r), 1);
	g = Math.min(Math.max(0, g), 1);
	b = Math.min(Math.max(0, b), 1);

	return [r * 255, g * 255, b * 255];
}


//extend rgb
rgb.yuv = function(rgb) {
	var r = rgb[0] / 255,
		g = rgb[1] / 255,
		b = rgb[2] / 255;

	var y = (r * 0.299) + (g * 0.587) + (b * 0.114);
	var u = (r * -0.14713) + (g * -0.28886) + (b * 0.436);
	var v = (r * 0.615) + (g * -0.51499) + (b * -0.10001);

	return [y, u, v];
};
```

**Comment by Grewer** [comment]
can use this lib: `@sishuguojixuefu/react-native-json-tree`

**Comment by Dean177** [comment]
I have just published 1.2.1 and didn't get this when running the examples, can anyone reproduce with the latest version?
If so it looks like @sishuguojixuefu might have fixed this issue in the base16 styling library, @sishuguojixuefu would you do a PR?

**Comment by Grewer** [comment]
I did not provide any PR,  I would like to know what version of RN you are using @Dean177

**Comment by Dean177** [comment]
Check out the Example folder, it uses 0.64

**Comment by tannermares** [comment]
@Dean177 I'm getting the same as well on RN 0.64 😬 
![image](https://user-images.githubusercontent.com/1806545/115124624-f5481a80-9f77-11eb-8aae-e021b014f27f.png)

**Comment by tannermares** [comment]
@Dean177 to test, I forked this repo and bumped `"react-base16-styling": "^0.8.0"` using the main repo and I'm not getting the error anymore. What was the reason for your original forking of that so I can make sure that still works too?

**Comment by Dean177** [comment]
I think it was due to incompatibilities in the version of babel used in the dependencies                                           (although it could have been something else, it was about 5 years ago now). I wouldn't worry about testing old versions.

**Comment by effektsvk** [comment]
Hey, @Dean177 , I'm not sure if you were the one publishing version `1.2.1` but the fix is not there. `package.json` still contains dependency `"react-base16-styling": "github:dean177/react-base16-styling#fbc6593"`.

For the time being I installed the package from master, but could you please release a new version? Thanks.

**Comment by Dean177** [comment]
@effektsvk 1.2.2 is out now
