### ISSUE TITLE
Should be nice to have an npm dependency

### ISSUE THREAD

**Issue by symis84** [Dean177/react-native-json-tree#152]
https://github.com/Dean177/react-native-json-tree/blob/ae81411bd98371b8fb342c0bf1431e0ed6969044/package.json#L14

When you work on CI or some external system sometimes you are not allowed to have git installed in the machine. If we can use an NPM dependency rather than "git" should be better.

thanks
Simone

**Comment by Dean177** [comment]
I would happily accept a PR that vendors that repository, I think if the author was going to update it  they would have done so by now 🙂

**Comment by symis84** [comment]
done.

thanks
