### ISSUE TITLE
[Depreciation] JSONArrow: DefaultProps will be removed from function components in a future major release

### ISSUE THREAD

**Issue by DylanBorchert** [Dean177/react-native-json-tree#160]
[This](https://github.com/Dean177/react-native-json-tree/blob/master/src/JSONArrow.js#L26) line is causing an error on render.

`Warning: JSONArrow: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

Would you merge a fix if I were to create a PR @Dean177?

**Comment by Dean177** [comment]
Sure thing, thanks

**Comment by trajano** [comment]
You also need it in node_modules/react-native-json-tree/src/Nodes.js

https://github.com/trajano/expo-experiments/blob/master/patches/react-native-json-tree%2B1.3.0.patch
