### ISSUE TITLE
JSONTree组件 iOS和harmony上collectionLimit属性设置不生效

### ISSUE THREAD

**Issue by Panlichen1996** [Dean177/react-native-json-tree#163]
iOS和harmony上collectionLimit属性设置不生效，JSONTree依旧展示实际的节点数，而非所设置的限制数量。

**Comment by Dean177** [comment]
I only speak english so can't help with this.

**Comment by Panlichen1996** [comment]
> I only speak english so can't help with this.

Thank you very much for replying to me，Dean!

I mean the  `collectionLimit` of props that did not work on `JsonTree`

I wish only 5 children show as I set.
But  `collectionLimit`  didn't work, so I can see all children in my JSONTree.

You can see this issue in the picture below

![image](https://github.com/user-attachments/assets/81f37364-5625-4ffd-8fe5-76a93a8e5a1d)

This is my code.
```
const data6 = {
    users: Array.from({length: 100}, (_, i) => ({id: i, name: `User ${i}`})),
  };
.......
 <View>
        <JSONTree data={data6} collectionLimit={5} />
 </View>
```
